### ISSUE TITLE
Add Minimal Documentation PLEASE

### ISSUE THREAD

**Issue by alpaslan-exe** [kahnwong/music-lyrics-tagger#5]
Hey there!
This might be a project that you created for the lols but I stumbled upon it and would love to use it, however, because there's no documentation I have no clue what anything does or how to debug errors the script throws at me. If you would be so kind as to provide some documentation that would mean a lot.
Thanks!

**Comment by kahnwong** [comment]
Hi, I completely forgot to specify required env, so that's on me.

Readme updated is live <https://github.com/kahnwong/music-lyrics-tagger/commit/fdf1005663cbc609920841e0c79f2a095f924e89>, please let me know if you want more information in the readme.

**Comment by alpaslan-exe** [comment]
No problem! 
Thank you for clarifying the variables I greatly appreciate it. Would you mind if I made a GUI based on your code at some point in time probably in a few months?
Best,

**Comment by kahnwong** [comment]
No at all! I'm very bad with GUI stuff, I would be more than happy if someone want to add GUI to this project!
